/*
 * 
 */

#ifndef __HI_COMM_IVE_H__
#define __HI_COMM_IVE_H__

#include "hi_type.h"
#include "hi_errno.h"
#include "comm_ive.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_U0Q8 GK_U0Q8
#define HI_U1Q7 GK_U1Q7
#define HI_U5Q3 GK_U5Q3
#define HI_U3Q5 GK_U3Q5
#define HI_U0Q16 GK_U0Q16
#define HI_U4Q12 GK_U4Q12
#define HI_U6Q10 GK_U6Q10
#define HI_U8Q8 GK_U8Q8
#define HI_U9Q7 GK_U9Q7
#define HI_U12Q4 GK_U12Q4
#define HI_U14Q2 GK_U14Q2
#define HI_U5Q11 GK_U5Q11
#define HI_U1Q15 GK_U1Q15
#define HI_U2Q14 GK_U2Q14
#define HI_UFP16 GK_UFP16
#define HI_S9Q7 GK_S9Q7
#define HI_S14Q2 GK_S14Q2
#define HI_S1Q15 GK_S1Q15
#define HI_U22Q10 GK_U22Q10
#define HI_U25Q7 GK_U25Q7
#define HI_U21Q11 GK_U21Q11
#define HI_U14Q18 GK_U14Q18
#define HI_U8Q24 GK_U8Q24
#define HI_U4Q28 GK_U4Q28
#define HI_S25Q7 GK_S25Q7
#define HI_S16Q16 GK_S16Q16
#define HI_S14Q18 GK_S14Q18
#define HI_S20Q12 GK_S20Q12
#define HI_S24Q8 GK_S24Q8
#define HI_U8Q4F4 GK_U8Q4F4
#define HI_ERR_IVE_INVALID_DEVID ERR_CODE_IVE_INVALID_DEVID
#define HI_ERR_IVE_INVALID_CHNID ERR_CODE_IVE_INVALID_CHNID
#define HI_ERR_IVE_ILLEGAL_PARAM ERR_CODE_IVE_ILLEGAL_PARAM
#define HI_ERR_IVE_EXIST ERR_CODE_IVE_EXIST
#define HI_ERR_IVE_UNEXIST ERR_CODE_IVE_UNEXIST
#define HI_ERR_IVE_NULL_PTR ERR_CODE_IVE_NULL_PTR
#define HI_ERR_IVE_NOT_CONFIG ERR_CODE_IVE_NOT_CONFIG
#define HI_ERR_IVE_NOT_SURPPORT ERR_CODE_IVE_NOT_SURPPORT
#define HI_ERR_IVE_NOT_PERM ERR_CODE_IVE_NOT_PERM
#define HI_ERR_IVE_NOMEM ERR_CODE_IVE_NOMEM
#define HI_ERR_IVE_NOBUF ERR_CODE_IVE_NOBUF
#define HI_ERR_IVE_BUF_EMPTY ERR_CODE_IVE_BUF_EMPTY
#define HI_ERR_IVE_BUF_FULL ERR_CODE_IVE_BUF_FULL
#define HI_ERR_IVE_NOTREADY ERR_CODE_IVE_NOTREADY
#define HI_ERR_IVE_BADADDR ERR_CODE_IVE_BADADDR
#define HI_ERR_IVE_BUSY ERR_CODE_IVE_BUSY
#define HI_ERR_IVE_SYS_TIMEOUT ERR_CODE_IVE_SYS_TIMEOUT
#define HI_ERR_IVE_QUERY_TIMEOUT ERR_CODE_IVE_QUERY_TIMEOUT
#define HI_ERR_IVE_OPEN_FILE ERR_CODE_IVE_OPEN_FILE
#define HI_ERR_IVE_READ_FILE ERR_CODE_IVE_READ_FILE
#define HI_ERR_IVE_WRITE_FILE ERR_CODE_IVE_WRITE_FILE
#define HI_ERR_IVE_BUS_ERR ERR_CODE_IVE_BUS_ERR
#define HI_ERR_FD_INVALID_DEVID ERR_CODE_FD_INVALID_DEVID
#define HI_ERR_FD_INVALID_CHNID ERR_CODE_FD_INVALID_CHNID
#define HI_ERR_FD_ILLEGAL_PARAM ERR_CODE_FD_ILLEGAL_PARAM
#define HI_ERR_FD_EXIST ERR_CODE_FD_EXIST
#define HI_ERR_FD_UNEXIST ERR_CODE_FD_UNEXIST
#define HI_ERR_FD_NULL_PTR ERR_CODE_FD_NULL_PTR
#define HI_ERR_FD_NOT_CONFIG ERR_CODE_FD_NOT_CONFIG
#define HI_ERR_FD_NOT_SURPPORT ERR_CODE_FD_NOT_SURPPORT
#define HI_ERR_FD_NOT_PERM ERR_CODE_FD_NOT_PERM
#define HI_ERR_FD_NOMEM ERR_CODE_FD_NOMEM
#define HI_ERR_FD_NOBUF ERR_CODE_FD_NOBUF
#define HI_ERR_FD_BUF_EMPTY ERR_CODE_FD_BUF_EMPTY
#define HI_ERR_FD_BUF_FULL ERR_CODE_FD_BUF_FULL
#define HI_ERR_FD_NOTREADY ERR_CODE_FD_NOTREADY
#define HI_ERR_FD_BADADDR ERR_CODE_FD_BADADDR
#define HI_ERR_FD_BUSY ERR_CODE_FD_BUSY
#define HI_ERR_FD_SYS_TIMEOUT ERR_CODE_FD_SYS_TIMEOUT
#define HI_ERR_FD_CFG ERR_CODE_FD_CFG
#define HI_ERR_FD_FACE_NUM_OVER ERR_CODE_FD_FACE_NUM_OVER
#define HI_ERR_FD_OPEN_FILE ERR_CODE_FD_OPEN_FILE
#define HI_ERR_FD_READ_FILE ERR_CODE_FD_READ_FILE
#define HI_ERR_FD_WRITE_FILE ERR_CODE_FD_WRITE_FILE
#define HI_ERR_ODT_INVALID_CHNID ERR_CODE_ODT_INVALID_CHNID
#define HI_ERR_ODT_EXIST ERR_CODE_ODT_EXIST
#define HI_ERR_ODT_UNEXIST ERR_CODE_ODT_UNEXIST
#define HI_ERR_ODT_NOT_PERM ERR_CODE_ODT_NOT_PERM
#define HI_ERR_ODT_NOTREADY ERR_CODE_ODT_NOTREADY
#define HI_ERR_ODT_BUSY ERR_CODE_ODT_BUSY

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMM_IVE_H__ */
