/*
 * 
 */

#ifndef __HI_COMM_AENC_H__
#define __HI_COMM_AENC_H__

#include "hi_type.h"
#include "hi_common.h"
#include "hi_comm_aio.h"
#include "comm_aenc.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_ERR_AENC_INVALID_DEVID ERR_CODE_AENC_INVALID_DEVID
#define HI_ERR_AENC_INVALID_CHNID ERR_CODE_AENC_INVALID_CHNID
#define HI_ERR_AENC_ILLEGAL_PARAM ERR_CODE_AENC_ILLEGAL_PARAM
#define HI_ERR_AENC_EXIST ERR_CODE_AENC_EXIST
#define HI_ERR_AENC_UNEXIST ERR_CODE_AENC_UNEXIST
#define HI_ERR_AENC_NULL_PTR ERR_CODE_AENC_NULL_PTR
#define HI_ERR_AENC_NOT_CONFIG ERR_CODE_AENC_NOT_CONFIG
#define HI_ERR_AENC_NOT_SUPPORT ERR_CODE_AENC_NOT_SUPPORT
#define HI_ERR_AENC_NOT_PERM ERR_CODE_AENC_NOT_PERM
#define HI_ERR_AENC_NOMEM ERR_CODE_AENC_NOMEM
#define HI_ERR_AENC_NOBUF ERR_CODE_AENC_NOBUF
#define HI_ERR_AENC_BUF_EMPTY ERR_CODE_AENC_BUF_EMPTY
#define HI_ERR_AENC_BUF_FULL ERR_CODE_AENC_BUF_FULL
#define HI_ERR_AENC_SYS_NOTREADY ERR_CODE_AENC_SYS_NOTREADY
#define HI_ERR_AENC_ENCODER_ERR ERR_CODE_AENC_ENCODER_ERR
#define HI_ERR_AENC_VQE_ERR ERR_CODE_AENC_VQE_ERR

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMM_AENC_H__ */
