/*
 * 
 */

#ifndef __HI_COMMON_CIPHER_H__
#define __HI_COMMON_CIPHER_H__

#include "common_cipher.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define  HI_ERR_CIPHER_NOT_INIT               ERR_CIPHER_NOT_INIT
#define  HI_ERR_CIPHER_INVALID_HANDLE         ERR_CIPHER_INVALID_HANDLE
#define  HI_ERR_CIPHER_INVALID_POINT          ERR_CIPHER_INVALID_POINT
#define  HI_ERR_CIPHER_INVALID_PARA           ERR_CIPHER_INVALID_PARA
#define  HI_ERR_CIPHER_FAILED_INIT            ERR_CIPHER_FAILED_INIT
#define  HI_ERR_CIPHER_FAILED_GETHANDLE       ERR_CIPHER_FAILED_GETHANDLE
#define  HI_ERR_CIPHER_FAILED_RELEASEHANDLE   ERR_CIPHER_FAILED_RELEASEHANDLE
#define  HI_ERR_CIPHER_FAILED_CONFIGAES       ERR_CIPHER_FAILED_CONFIGAES
#define  HI_ERR_CIPHER_FAILED_CONFIGDES       ERR_CIPHER_FAILED_CONFIGDES
#define  HI_ERR_CIPHER_FAILED_ENCRYPT         ERR_CIPHER_FAILED_ENCRYPT
#define  HI_ERR_CIPHER_FAILED_DECRYPT         ERR_CIPHER_FAILED_DECRYPT
#define  HI_ERR_CIPHER_BUSY                   ERR_CIPHER_BUSY
#define  HI_ERR_CIPHER_NO_AVAILABLE_RNG       ERR_CIPHER_NO_AVAILABLE_RNG
#define  HI_ERR_CIPHER_FAILED_MEM             ERR_CIPHER_FAILED_MEM
#define  HI_ERR_CIPHER_UNAVAILABLE            ERR_CIPHER_UNAVAILABLE
#define  HI_ERR_CIPHER_OVERFLOW               ERR_CIPHER_OVERFLOW
#define  HI_ERR_CIPHER_HARD_STATUS            ERR_CIPHER_HARD_STATUS
#define  HI_ERR_CIPHER_TIMEOUT                ERR_CIPHER_TIMEOUT
#define  HI_ERR_CIPHER_UNSUPPORTED            ERR_CIPHER_UNSUPPORTED
#define  HI_ERR_CIPHER_REGISTER_IRQ           ERR_CIPHER_REGISTER_IRQ
#define  HI_ERR_CIPHER_ILLEGAL_UUID           ERR_CIPHER_ILLEGAL_UUID
#define  HI_ERR_CIPHER_ILLEGAL_KEY            ERR_CIPHER_ILLEGAL_KEY
#define  HI_ERR_CIPHER_INVALID_ADDR           ERR_CIPHER_INVALID_ADDR
#define  HI_ERR_CIPHER_INVALID_LENGTH         ERR_CIPHER_INVALID_LENGTH
#define  HI_ERR_CIPHER_ILLEGAL_DATA           ERR_CIPHER_ILLEGAL_DATA
#define  HI_ERR_CIPHER_RSA_SIGN               ERR_CIPHER_RSA_SIGN
#define  HI_ERR_CIPHER_RSA_VERIFY             ERR_CIPHER_RSA_VERIFY
#define  HI_ERR_CIPHER_MEMSET_S_FAILED        ERR_CIPHER_MEMSET_S_FAILED
#define  HI_ERR_CIPHER_MEMCPY_S_FAILED        ERR_CIPHER_MEMCPY_S_FAILED
#define  HI_ERR_CIPHER_RSA_CRYPT_FAILED       ERR_CIPHER_RSA_CRYPT_FAILED

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMMON_CIPHER_H__ */
