/*
  Copyright (c), 2001-2021, CHANGJIANG Tech. Co., Ltd.
*/

#ifndef __AACENC_H__
#define __AACENC_H__

#include "hi_type.h"
#include "audio_aacenc.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_AACENC_OK AACENC_CODE_OK
#define HI_AACENC_INVALID_HANDLE AACENC_CODE_INVALID_HANDLE
#define HI_AACENC_MEMORY_ERROR AACENC_CODE_MEMORY_ERROR
#define HI_AACENC_UNSUPPORTED_PARAMETER AACENC_CODE_UNSUPPORTED_PARAMETER
#define HI_AACENC_INVALID_CONFIG AACENC_CODE_INVALID_CONFIG
#define HI_AACENC_INIT_ERROR AACENC_CODE_INIT_ERROR
#define HI_AACENC_INIT_AAC_ERROR AACENC_CODE_INIT_AAC_ERROR
#define HI_AACENC_INIT_SBR_ERROR AACENC_CODE_INIT_SBR_ERROR
#define HI_AACENC_INIT_TP_ERROR AACENC_CODE_INIT_TP_ERROR
#define HI_AACENC_INIT_META_ERROR AACENC_CODE_INIT_META_ERROR
#define HI_AACENC_ENCODE_ERROR AACENC_CODE_ENCODE_ERROR
#define HI_AACENC_ENCODE_EOF AACENC_CODE_ENCODE_EOF

HI_S32 HI_AACENC_GetVersion(AACENC_VERSION_S *pVersion);

HI_VOID *HI_AAC_SBRENC_GetHandle(HI_VOID);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __AACENC_H__ */
