/*
 * 
 */

#ifndef __HI_COMM_VI_H__
#define __HI_COMM_VI_H__

#include "hi_common.h"
#include "hi_errno.h"
#include "hi_comm_video.h"
#include "hi_comm_gdc.h"
#include "comm_vi.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_ERR_VI_INVALID_PARA ERR_CODE_VI_INVALID_PARA
#define HI_ERR_VI_INVALID_DEVID ERR_CODE_VI_INVALID_DEVID
#define HI_ERR_VI_INVALID_PIPEID ERR_CODE_VI_INVALID_PIPEID
#define HI_ERR_VI_INVALID_STITCHGRPID ERR_CODE_VI_INVALID_STITCHGRPID
#define HI_ERR_VI_INVALID_CHNID ERR_CODE_VI_INVALID_CHNID
#define HI_ERR_VI_INVALID_NULL_PTR ERR_CODE_VI_INVALID_NULL_PTR
#define HI_ERR_VI_FAILED_NOTCONFIG ERR_CODE_VI_FAILED_NOTCONFIG
#define HI_ERR_VI_SYS_NOTREADY ERR_CODE_VI_SYS_NOTREADY
#define HI_ERR_VI_BUF_EMPTY ERR_CODE_VI_BUF_EMPTY
#define HI_ERR_VI_BUF_FULL ERR_CODE_VI_BUF_FULL
#define HI_ERR_VI_NOMEM ERR_CODE_VI_NOMEM
#define HI_ERR_VI_NOT_SUPPORT ERR_CODE_VI_NOT_SUPPORT
#define HI_ERR_VI_BUSY ERR_CODE_VI_BUSY
#define HI_ERR_VI_NOT_PERM ERR_CODE_VI_NOT_PERM
#define HI_ERR_VI_FAILED_NOTENABLE ERR_CODE_VI_FAILED_NOTENABLE
#define HI_ERR_VI_FAILED_NOTDISABLE ERR_CODE_VI_FAILED_NOTDISABLE
#define HI_ERR_VI_FAILED_CHNOTDISABLE ERR_CODE_VI_FAILED_CHNOTDISABLE
#define HI_ERR_VI_CFG_TIMEOUT ERR_CODE_VI_CFG_TIMEOUT
#define HI_ERR_VI_NORM_UNMATCH ERR_CODE_VI_NORM_UNMATCH
#define HI_ERR_VI_INVALID_WAYID ERR_CODE_VI_INVALID_WAYID
#define HI_ERR_VI_INVALID_PHYCHNID ERR_CODE_VI_INVALID_PHYCHNID
#define HI_ERR_VI_FAILED_NOTBIND ERR_CODE_VI_FAILED_NOTBIND
#define HI_ERR_VI_FAILED_BINDED ERR_CODE_VI_FAILED_BINDED
#define HI_ERR_VI_PIPE_EXIST ERR_CODE_VI_PIPE_EXIST
#define HI_ERR_VI_PIPE_UNEXIST ERR_CODE_VI_PIPE_UNEXIST

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMM_VI_H__ */
