/*
 * 
 */

#ifndef __HI_COMM_REGION_H__
#define __HI_COMM_REGION_H__

#include "hi_common.h"
#include "hi_comm_video.h"
#include "hi_errno.h"
#include "hi_defines.h"
#include "comm_region.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_NOTICE_RGN_BUFFER_CHANGE NOTICE_RGN_BUFFER_CHANGE
#define HI_ERR_RGN_INVALID_DEVID ERR_CODE_RGN_INVALID_DEVID
#define HI_ERR_RGN_INVALID_CHNID ERR_CODE_RGN_INVALID_CHNID
#define HI_ERR_RGN_ILLEGAL_PARAM ERR_CODE_RGN_ILLEGAL_PARAM
#define HI_ERR_RGN_EXIST ERR_CODE_RGN_EXIST
#define HI_ERR_RGN_UNEXIST ERR_CODE_RGN_UNEXIST
#define HI_ERR_RGN_NULL_PTR ERR_CODE_RGN_NULL_PTR
#define HI_ERR_RGN_NOT_CONFIG ERR_CODE_RGN_NOT_CONFIG
#define HI_ERR_RGN_NOT_SUPPORT ERR_CODE_RGN_NOT_SUPPORT
#define HI_ERR_RGN_NOT_PERM ERR_CODE_RGN_NOT_PERM
#define HI_ERR_RGN_NOMEM ERR_CODE_RGN_NOMEM
#define HI_ERR_RGN_NOBUF ERR_CODE_RGN_NOBUF
#define HI_ERR_RGN_BUF_EMPTY ERR_CODE_RGN_BUF_EMPTY
#define HI_ERR_RGN_BUF_FULL ERR_CODE_RGN_BUF_FULL
#define HI_ERR_RGN_BADADDR ERR_CODE_RGN_BADADDR
#define HI_ERR_RGN_BUSY ERR_CODE_RGN_BUSY
#define HI_ERR_RGN_NOTREADY ERR_CODE_RGN_NOTREADY

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMM_REGION_H__ */
