/*
 * 
 */

#ifndef __HI_COMM_AIO_H__
#define __HI_COMM_AIO_H__

#include "hi_common.h"
#include "hi_errno.h"
#include "comm_aio.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_ERR_AIO_ILLEGAL_PARAM ERR_CODE_AIO_ILLEGAL_PARAM
#define HI_ERR_AIO_NULL_PTR ERR_CODE_AIO_NULL_PTR
#define HI_ERR_AIO_NOT_PERM ERR_CODE_AIO_NOT_PERM
#define HI_ERR_AIO_REGISTER_ERR ERR_CODE_AIO_REGISTER_ERR
#define HI_ERR_AI_INVALID_DEVID ERR_CODE_AI_INVALID_DEVID
#define HI_ERR_AI_INVALID_CHNID ERR_CODE_AI_INVALID_CHNID
#define HI_ERR_AI_ILLEGAL_PARAM ERR_CODE_AI_ILLEGAL_PARAM
#define HI_ERR_AI_NULL_PTR ERR_CODE_AI_NULL_PTR
#define HI_ERR_AI_NOT_CONFIG ERR_CODE_AI_NOT_CONFIG
#define HI_ERR_AI_NOT_SUPPORT ERR_CODE_AI_NOT_SUPPORT
#define HI_ERR_AI_NOT_PERM ERR_CODE_AI_NOT_PERM
#define HI_ERR_AI_NOT_ENABLED ERR_CODE_AI_NOT_ENABLED
#define HI_ERR_AI_NOMEM ERR_CODE_AI_NOMEM
#define HI_ERR_AI_NOBUF ERR_CODE_AI_NOBUF
#define HI_ERR_AI_BUF_EMPTY ERR_CODE_AI_BUF_EMPTY
#define HI_ERR_AI_BUF_FULL ERR_CODE_AI_BUF_FULL
#define HI_ERR_AI_SYS_NOTREADY ERR_CODE_AI_SYS_NOTREADY
#define HI_ERR_AI_BUSY ERR_CODE_AI_BUSY
#define HI_ERR_AI_VQE_ERR ERR_CODE_AI_VQE_ERR
#define HI_ERR_AO_INVALID_DEVID ERR_CODE_AO_INVALID_DEVID
#define HI_ERR_AO_INVALID_CHNID ERR_CODE_AO_INVALID_CHNID
#define HI_ERR_AO_ILLEGAL_PARAM ERR_CODE_AO_ILLEGAL_PARAM
#define HI_ERR_AO_NULL_PTR ERR_CODE_AO_NULL_PTR
#define HI_ERR_AO_NOT_CONFIG ERR_CODE_AO_NOT_CONFIG
#define HI_ERR_AO_NOT_SUPPORT ERR_CODE_AO_NOT_SUPPORT
#define HI_ERR_AO_NOT_PERM ERR_CODE_AO_NOT_PERM
#define HI_ERR_AO_NOT_ENABLED ERR_CODE_AO_NOT_ENABLED
#define HI_ERR_AO_NOMEM ERR_CODE_AO_NOMEM
#define HI_ERR_AO_NOBUF ERR_CODE_AO_NOBUF
#define HI_ERR_AO_BUF_EMPTY ERR_CODE_AO_BUF_EMPTY
#define HI_ERR_AO_BUF_FULL ERR_CODE_AO_BUF_FULL
#define HI_ERR_AO_SYS_NOTREADY ERR_CODE_AO_SYS_NOTREADY
#define HI_ERR_AO_BUSY ERR_CODE_AO_BUSY
#define HI_ERR_AO_VQE_ERR ERR_CODE_AO_VQE_ERR

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMM_AIO_H__ */
