/*
 * 
 */

#ifndef __HI_COMM_ADEC_H__
#define __HI_COMM_ADEC_H__

#include "hi_type.h"
#include "hi_common.h"
#include "hi_comm_aio.h"
#include "comm_adec.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define HI_ERR_ADEC_INVALID_DEVID ERR_CODE_ADEC_INVALID_DEVID
#define HI_ERR_ADEC_INVALID_CHNID ERR_CODE_ADEC_INVALID_CHNID
#define HI_ERR_ADEC_ILLEGAL_PARAM ERR_CODE_ADEC_ILLEGAL_PARAM
#define HI_ERR_ADEC_EXIST ERR_CODE_ADEC_EXIST
#define HI_ERR_ADEC_UNEXIST ERR_CODE_ADEC_UNEXIST
#define HI_ERR_ADEC_NULL_PTR ERR_CODE_ADEC_NULL_PTR
#define HI_ERR_ADEC_NOT_CONFIG ERR_CODE_ADEC_NOT_CONFIG
#define HI_ERR_ADEC_NOT_SUPPORT ERR_CODE_ADEC_NOT_SUPPORT
#define HI_ERR_ADEC_NOT_PERM ERR_CODE_ADEC_NOT_PERM
#define HI_ERR_ADEC_NOMEM ERR_CODE_ADEC_NOMEM
#define HI_ERR_ADEC_NOBUF ERR_CODE_ADEC_NOBUF
#define HI_ERR_ADEC_BUF_EMPTY ERR_CODE_ADEC_BUF_EMPTY
#define HI_ERR_ADEC_BUF_FULL ERR_CODE_ADEC_BUF_FULL
#define HI_ERR_ADEC_SYS_NOTREADY ERR_CODE_ADEC_SYS_NOTREADY
#define HI_ERR_ADEC_DECODER_ERR ERR_CODE_ADEC_DECODER_ERR
#define HI_ERR_ADEC_BUF_LACK ERR_CODE_ADEC_BUF_LACK

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif /* __HI_COMM_ADEC_H__ */
