/*
 * 
 */

#ifndef __HI_MIPI_H__
#define __HI_MIPI_H__
#include "mipi.h"

#define HI_MSG MSG
#define HI_ERR ERR
#define HI_MIPI_WDR_MODE_NONE MIPI_WDR_MODE_NONE
#define HI_MIPI_WDR_MODE_VC MIPI_WDR_MODE_VC
#define HI_MIPI_WDR_MODE_DT MIPI_WDR_MODE_DT
#define HI_MIPI_WDR_MODE_DOL MIPI_WDR_MODE_DOL
#define HI_WDR_MODE_NONE WDR_MODE_NONE
#define HI_WDR_MODE_2F IN_WDR_MODE_2F
#define HI_WDR_MODE_3F IN_WDR_MODE_3F
#define HI_WDR_MODE_4F IN_WDR_MODE_4F
#define HI_WDR_MODE_DOL_2F IN_WDR_MODE_DOL_2F
#define HI_WDR_MODE_DOL_3F IN_WDR_MODE_DOL_3F
#define HI_WDR_MODE_DOL_4F IN_WDR_MODE_DOL_4F
#define HI_MIPI_IOC_MAGIC MIPI_IOC_MAGIC
#define HI_MIPI_SET_DEV_ATTR MIPI_SET_DEV_ATTR
#define HI_MIPI_SET_PHY_CMVMODE MIPI_SET_PHY_CMVMODE
#define HI_MIPI_RESET_SENSOR MIPI_RESET_SENSOR
#define HI_MIPI_UNRESET_SENSOR MIPI_UNRESET_SENSOR
#define HI_MIPI_RESET_MIPI MIPI_RESET_MIPI
#define HI_MIPI_UNRESET_MIPI MIPI_UNRESET_MIPI
#define HI_MIPI_RESET_SLVS MIPI_RESET_SLVS
#define HI_MIPI_UNRESET_SLVS MIPI_UNRESET_SLVS
#define HI_MIPI_SET_HS_MODE MIPI_SET_HS_MODE
#define HI_MIPI_ENABLE_MIPI_CLOCK MIPI_ENABLE_MIPI_CLOCK
#define HI_MIPI_DISABLE_MIPI_CLOCK MIPI_DISABLE_MIPI_CLOCK
#define HI_MIPI_ENABLE_SLVS_CLOCK MIPI_ENABLE_SLVS_CLOCK
#define HI_MIPI_DISABLE_SLVS_CLOCK MIPI_DISABLE_SLVS_CLOCK
#define HI_MIPI_ENABLE_SENSOR_CLOCK MIPI_ENABLE_SENSOR_CLOCK
#define HI_MIPI_DISABLE_SENSOR_CLOCK MIPI_DISABLE_SENSOR_CLOCK

#endif /* __HI_MIPI_H__ */
